apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-qizs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-qizs
    app.kubernetes.io/part-of: ci1t-830-0032-app
  name: devfile-sample-qizs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-qizs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-qizs
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0032-tenant/ci1t-830-0032-app/devfile-sample-qizs@sha256:57311afe45307b7c59b49cf0de19eef14be8a34e3dfd882b53802ac253f7182b
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
